# FRAMEBUFFER CONSTANTS
WIDTH = 800
HEIGTH = 600
NAME = 'MINECRAFT 2D'

# COLOR CONSTANTS
BACKGROUND_COLOR = (51, 37, 184)
BACKGROUND_IMG = 'E:\\Working place\\NEW20202\\MINECRAFT_PYTHON\\img\\bgr_img.jpg'
SELECTED_COLOR = (225,225,225)
UNSELECTED_COLOR = (0,0,0)

# AUDIO CONSTANTS
BACKGROUND_AUDIO = 'E:\\Working place\\NEW20202\\MINECRAFT_PYTHON\\audio\\bgr_audio.mp3'

# FONT CONSTANTS
FONT = "E:\\Working place\\NEW20202\\MINECRAFT_PYTHON\\font\\AC.ttf"
TILTE_FONT_SIZE = 90
OPTION_FONT_SIZE = 40